services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Letsema
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # This ensures node_modules from the container is used
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]  # Make sure this matches a script in your package.json
